name: Deploy ebm Central to Hostinger

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy-backend:
    name: 🚀 Deploy Backend to Hostinger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Backend via SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete --timeout=120"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: 65002
          TARGET: "/home/u200841033/domains/ebfic.store/public_html/central/"
          SOURCE: "backend/"
